### ISSUE TITLE
Implementing Zenject

### ISSUE THREAD

**Issue by gkoehl** [RomanZhu/Match-Line-Entitas-ECS#1]
https://github.com/RomanZhu/Match-Line-Entitas-ECS/blob/0de7a215ccca67f3272f666d7e4a6b6c795c1864/Assets/Sources/GameController.cs#L19

Awesome work on this implementation of Entitas.  I have a question for you.  How would you go about implementing Zenject on this project?  Would you need another GameObject for the MonoInstaller?  How would you make sure that the injections ran before the GameController?

**Comment by RomanZhu** [comment]
Hey, thanks :)
I had an option to use it, but decided to go without it, so beginners could easily track everything down.

> Would you need another GameObject for the MonoInstaller?

Yep, I would use another GameObject for that.

> How would you make sure that the injections ran before the GameController?

One way is through Script Execution Order (move MonoInstaller to -500 for example).
Another way is install bindings on Awake and make sure first use of injected values is on Start or later.

Do not use Contexts.sharedInstance tho :D This will create a separate instance, which can lead to malfunctioning.

**Comment by gkoehl** [comment]
Thank you for the insight.  You've pointed me in the right direction, and I'll look to implement that on my own.  I think Zenject + Entitas is the way to go until Unity finishes the Pure ECS solution.
